var ImageId = {
  IMAGE_QUESTION_DARK: 0,
  IMAGE_SUNNY_DARK: 1,
  IMAGE_CLEAR_NIGHT_DARK: 2,
  IMAGE_PARTLY_CLOUDY_DARK: 3,
  IMAGE_PARTLY_CLOUDY_NIGHT_DARK: 4,
  IMAGE_CLOUDY_DARK: 5,
  IMAGE_HEAVY_RAIN_DARK: 6,
  IMAGE_HEAVY_SNOW_DARK: 7,
  IMAGE_RAIN_SNOW_DARK: 8,
  IMAGE_THUNDERSTORM_DARK: 9
};

module.exports = ImageId;
